baseURL = "https://openair.city/"
languageCode = "en-us"
title = "OpenAir - Карта качества воздуха"
disableKinds=[ "RSS", "sitemap", "taxonomyTerm" ]
publishDir = "../release"

[params]
    openair_js = ["js/init.js", "js/legend.js", "js/api.js", "js/map.js", "js/permalink.js", "js/timeline.js", "js/timer.js"]
    # api_url = "http://localhost:8081/v1"
    api_url = "https://api.openair.city/v1"
    mapbox_token = "pk.eyJ1IjoiM2NreSIsImEiOiJjancwYnM4NzIwOG43M3lzMnljZGppbmo5In0.Mtp-J2o-f_5c4qs-X6kCOQ"
    map_center = "[48.709144, 44.506645]"
    map_zoom = 13
    map_refresh_period = "30000" # in milliseconds
    map_charts_time_window = "24" # in hours
